// Register only generated plates actually present; no broken-image promises.
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
const plan=JSON.parse(readFileSync('docs/region-plan.json'));
const registry={};
const manifest=JSON.parse(readFileSync('docs/art-manifest.json'));
for(const region of plan){
  const file=`public/art/${region.key}.png`;
  if(!existsSync(file))continue;
  for(const [cell,rooms] of region.rooms.entries())for(const id of rooms)
    registry[id]={art:region.key,cell,caption:'',objects:[],hotspots:[]};
  const bytes=readFileSync(file);
  const entry={file,sha256:createHash('sha256').update(bytes).digest('hex'),width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),generator:'built-in image-generation tool',created:'2026-09-09',status:'regional environment atlas; stateful props separate',prompt:`docs/generated/${region.key}.json`};
  const i=manifest.findIndex(x=>x.file===file);if(i<0)manifest.push(entry);else manifest[i]=entry;
}
writeFileSync('src/regions.js','// Generated by scripts/catalog-art.mjs from present assets.\nexport const regions = '+JSON.stringify(registry,null,2)+';\n');
writeFileSync('docs/art-manifest.json',JSON.stringify(manifest,null,2)+'\n');
console.log(`${Object.keys(registry).length} regional room mappings registered`);
