// Generated by scripts/catalog-art.mjs from present assets.
export const regions = {
  "2": {
    "art": "temple-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "3": {
    "art": "mines-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "4": {
    "art": "temple-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "5": {
    "art": "surface-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "8": {
    "art": "mine-chambers-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "11": {
    "art": "dome-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "13": {
    "art": "dome-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "16": {
    "art": "mines-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "18": {
    "art": "dome-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "19": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "21": {
    "art": "canyon-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "22": {
    "art": "canyon-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "25": {
    "art": "caves-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "30": {
    "art": "river-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "31": {
    "art": "mine-oddities-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "32": {
    "art": "forest-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "34": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "37": {
    "art": "river-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "38": {
    "art": "dome-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "40": {
    "art": "waterways-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "42": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "45": {
    "art": "river-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "46": {
    "art": "mine-oddities-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "47": {
    "art": "rainbow-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "50": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "51": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "52": {
    "art": "mirror-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "53": {
    "art": "river-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "54": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "62": {
    "art": "caves-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "67": {
    "art": "waterways-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "69": {
    "art": "caves-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "72": {
    "art": "mines-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "74": {
    "art": "canyon-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "78": {
    "art": "late-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "81": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "82": {
    "art": "late-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "86": {
    "art": "waterways-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "87": {
    "art": "forest-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "89": {
    "art": "mine-chambers-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "90": {
    "art": "mines-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "93": {
    "art": "caves-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "95": {
    "art": "reservoir-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "102": {
    "art": "passages-two-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "104": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "110": {
    "art": "mirror-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "111": {
    "art": "waterways-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "112": {
    "art": "mines-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "117": {
    "art": "late-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "120": {
    "art": "dam-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "123": {
    "art": "reservoir-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "125": {
    "art": "rainbow-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "128": {
    "art": "forest-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "129": {
    "art": "temple-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "134": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "139": {
    "art": "passages-two-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "141": {
    "art": "forest-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "143": {
    "art": "forest-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "145": {
    "art": "passages-two-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "147": {
    "art": "forest-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "152": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "153": {
    "art": "forest-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "155": {
    "art": "river-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "156": {
    "art": "forest-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "158": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "160": {
    "art": "forest-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "161": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "162": {
    "art": "canyon-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "166": {
    "art": "river-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "167": {
    "art": "forest-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "170": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "171": {
    "art": "mine-oddities-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "173": {
    "art": "mines-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "174": {
    "art": "river-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "176": {
    "art": "caves-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "178": {
    "art": "dam-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "182": {
    "art": "river-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "184": {
    "art": "river-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "187": {
    "art": "surface-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "188": {
    "art": "mines-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "191": {
    "art": "reservoir-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "193": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "202": {
    "art": "rainbow-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "205": {
    "art": "dam-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "209": {
    "art": "surface-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "216": {
    "art": "late-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "218": {
    "art": "forest-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "221": {
    "art": "forest-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "224": {
    "art": "dam-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "228": {
    "art": "passages-two-atlas",
    "cell": 0,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "235": {
    "art": "mine-oddities-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "238": {
    "art": "surface-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "241": {
    "art": "temple-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "244": {
    "art": "rainbow-atlas",
    "cell": 3,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "245": {
    "art": "mine-chambers-atlas",
    "cell": 2,
    "caption": "",
    "objects": [],
    "hotspots": []
  },
  "249": {
    "art": "mine-chambers-atlas",
    "cell": 1,
    "caption": "",
    "objects": [],
    "hotspots": []
  }
};
